import type { Metadata } from 'next';
import '@/app/global.scss';
import { inter } from '@/app/ui/fonts';
import { Navbar } from '@/app/ui/Navbar';
import React from 'react';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialTheme = 'light';

    return (
        <html lang='en' data-theme={initialTheme}>
            <body className={`${inter.className} antialiased text-base-content bg-base-100`}>
                <Navbar initialTheme={initialTheme} />
                {children}
            </body>
        </html>
    );
}

