import type { Metadata } from 'next';
import './global.scss';
import { inter } from './ui/fonts';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' data-theme='light'>
            <body className={`${inter.className} antialiased`}>{children}</body>
        </html>
    );
}

